app <- ShinyDriver$new("../../", seed = 1234)
app$snapshotInit("level_plot")

app$setInputs(levelSel = "IA")
app$snapshot()
app$setInputs(levelSel = "IB")
app$snapshot()
app$setInputs(levelSel = "IB1")
app$snapshot()
app$setInputs(levelSel = "IB2")
app$snapshot()
app$setInputs(levelSel = "IIA")
app$snapshot()
app$setInputs(levelSel = "IIB")
app$snapshot()
app$setInputs(levelSel = "IIB1")
app$snapshot()
app$setInputs(levelSel = "IIIA")
app$snapshot()
app$setInputs(levelSel = "IIIB")
app$snapshot()
app$setInputs(levelSel = "IV")
app$snapshot()
app$setInputs(levelSel = "<NA>")
app$snapshot()
