app <- ShinyDriver$new("../../", seed = 1234)
app$snapshotInit("primary_plot_factor")

app$setInputs(levelSel = "IA")
app$snapshot()
app$setInputs(factorSel = "Sample_Type")
app$setInputs(levelSel = "cell line", wait_ = FALSE, values_ = FALSE)
app$snapshot()
app$setInputs(factorSel = "Cell_Type")
app$setInputs(levelSel = "adenocarcinoma", wait_ = FALSE, values_ = FALSE)
app$snapshot()
app$setInputs(factorSel = "Age", wait_ = FALSE, values_ = FALSE)
app$setInputs(levelSel = "<40")
app$snapshot()
app$setInputs(factorSel = "HPV", wait_ = FALSE, values_ = FALSE)
app$setInputs(levelSel = " 16")
app$snapshot()
